### ISSUE TITLE
raise a LinAlgError("singular matrix")

### ISSUE THREAD

**Issue by zengxianyu** [ruanxiang/mr_saliency#1]
in file MR.py, when computing aff = inv(D-self.weight_parameters['alpha']*W)

**Comment by ruanxiang** [comment]
What parameters did you use for the calculation?

**Comment by zengxianyu** [comment]
I use the default parameters given in the code

**Comment by ghost** [comment]
I also met this problem and I address it.
Since the problem is raised by singular matrix, which means the matrix is uninvertible, I add a eye matrix with 0.0001 to make the matrix be invertible.

**Comment by ruanxiang** [comment]
> I also met this problem and I address it.
> Since the problem is raised by singular matrix, which means the matrix is uninvertible, I add a eye matrix with 0.0001 to make the matrix be invertible.

Thank you. Can you submit the modification? I don't have time to maintain the source code, I am sorry for that

**Comment by ake020675** [comment]
I also met this problem when test with 'i2308394240.jpeg' in MIT1003 dataset

**Comment by ake020675** [comment]
> eye matrix with 0.0001
       
 change this:
aff = inv(D-self.weight_parameters['alpha']*W)
to:
aff = inv(D-self.weight_parameters['alpha']*W + 0.0001*np.eye(D.shape[0]) )

works for me

**Comment by ruanxiang** [comment]
Thank you @ake020675 , @dosthwrong  and other bug reporters. I am so sorry for late response and bug fix. To avoid singular matrix error, I use pinv()  instead of inv(). Please test if the updated version works well.

**Comment by ruanxiang** [comment]
Fix the bug by using pinv() instead of inv() for matrix inverse.
