### ISSUE TITLE
MR_boundary_saliency - ValueError: operands could not be broadcast together with shapes...

### ISSUE THREAD

**Issue by NeuralBricolage** [ruanxiang/mr_saliency#4]
in MR_boundary_saliency i keep getting this exception with all the images i tried (of various shapes, rectangular or square)
ex
<img width="904" alt="screen shot 2018-06-18 at 7 31 27 am" src="https://user-images.githubusercontent.com/4332614/41533768-f2cf0df0-72c9-11e8-8f90-4784e08be4cf.png">

thank you

**Comment by ruanxiang** [comment]
Could you please give me more details like how you use the library, image file information and so on?

**Comment by ruanxiang** [comment]
Fixed
